### ISSUE TITLE
Idea for named ic attributes to group actions per trigger

### ISSUE THREAD

**Issue by n3storm** [LeadDyno/intercooler-js#100]
This is just a first rough thought.

I need to do something on double click and another action on click.
How can we achieve having multiple actions related to multiple triggers? naming with ic-attr-nameA.

For example:
`<a ic-get-from="A" ic-trigger-on="click" ic-get-from-Another="B" ic-trigger-on-Another="dblclick">fuu</a>`

In this case **Another** attrs goes together, and no named attrs are **default** group.

Not sure what is better for visualizing group or attr parsing, at the beginning or at the end:
` ic-Another-get-from` vs.` ic-get-from-Another`

I cannot find more use cases but for triggers, including touch ones. But maybe somebody else find other uses.

What do you think? Is this too much of a burden for dom manipulating and ic-id accounting?

**Comment by carsongross** [comment]
Hi Nestor,

Could you wrap a second element around the anchor and put the trigger and get on that?  The event should bubble up and be handled, if I’m thinking properly (it’s the weekend here… :):

  <span  ic-get-from="B" ic-trigger-on="dblclick"><a ic-get-from="A" ic-trigger-on="click">fuu</a></span>

I think we should also maybe pass the triggering event name up to the server side as a parameter, so you can tailor your response to the request based on that (in addition to the target element, etc.)

Cheers,
Carson

On May 28, 2016 at 9:55:32 AM, Néstor Díaz Valencia (notifications@github.com) wrote:

This is just a first rough thought.

I need to do something on double click and another action on click.
How can we achieve having multiple actions related to multiple triggers? naming with ic-attr-nameA.

For example:
<a ic-get-from="A" ic-trigger-on="click" ic-get-from-Another="B" ic-trigger-on-Another="dblclick">fuu</a>

Not sure what is better for visualizeing group or attr parsing, at the beginning or at the end:
ic-Another-get-from vs.ic-get-from-Another

I cannot find more use cases but for triggers, including touch ones. But maybe somebody else find other uses.

What do you think? Is this too much of a burden for dom manipulating and ic-id accounting?

**Comment by carsongross** [comment]
Also, looking into it, it looks like you might need to do some javascript work to properly differentiate between the two events:

  http://stackoverflow.com/questions/5471291/javascript-with-jquery-click-and-double-click-on-same-element-different-effect

Cheers,
Carson
—
LeadDyno • Co-Founder
@carson_gross

On May 28, 2016 at 10:59:02 AM, Carson Gross (carsongross@gmail.com) wrote:

Hi Nestor,

Could you wrap a second element around the anchor and put the trigger and get on that?  The event should bubble up and be handled, if I’m thinking properly (it’s the weekend here… :):

  <span  ic-get-from="B" ic-trigger-on="dblclick"><a ic-get-from="A" ic-trigger-on="click">fuu</a></span>

I think we should also maybe pass the triggering event name up to the server side as a parameter, so you can tailor your response to the request based on that (in addition to the target element, etc.)

Cheers,
Carson

On May 28, 2016 at 9:55:32 AM, Néstor Díaz Valencia (notifications@github.com) wrote:

This is just a first rough thought.

I need to do something on double click and another action on click.
How can we achieve having multiple actions related to multiple triggers? naming with ic-attr-nameA.

For example:
<a ic-get-from="A" ic-trigger-on="click" ic-get-from-Another="B" ic-trigger-on-Another="dblclick">fuu</a>

Not sure what is better for visualizeing group or attr parsing, at the beginning or at the end:
ic-Another-get-from vs.ic-get-from-Another

I cannot find more use cases but for triggers, including touch ones. But maybe somebody else find other uses.

What do you think? Is this too much of a burden for dom manipulating and ic-id accounting?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or mute the thread.

--
You received this message because you are subscribed to the Google Groups "intercooler-js" group.
To unsubscribe from this group and stop receiving emails from it, send an email to intercooler-js+unsubscribe@googlegroups.com.
For more options, visit https://groups.google.com/d/optout.

**Comment by n3storm** [comment]
Yeah, thats the "problem" I propose to solve: extra javascript for a common behaviour in modern web apps to be used on mobile: typo or swipe, pinch or roll, etc.
http://www.w3schools.com/jquerymobile/jquerymobile_events_touch.asp

Anyway this is not a priority  for me (of course). Thanks for your weekend response Carson :D
