### ISSUE TITLE
scrolled-into-view loaded without scrolling element into view

### ISSUE THREAD

**Issue by Shrooma111** [LeadDyno/intercooler-js#119]
I'm having an issue with the scrolled-into-view trigger, it loads even if the element is not into view.

html snippet:
```

        <ul id="questionlist" class="list-group">
 
                    <li class="list-group-item"> <a href="/polls/1006/">Question 999</a></li>

                    <li class="list-group-item"> <a href="/polls/1005/">Question 998</a></li>
  
                    ....

                    <li class="list-group-item"> <a href="/polls/978/">Question 971</a></li>

                    <li ic-append-from="/polls/questions/30" ic-trigger-on="scrolled-into-view" ic-target="#questionlist" ic-indicator="#indicator" class="list-group-item"> <a href="/polls/977/">Question 997</a></li>

        </ul>
```

When using ic-trigger-on="click" this works as desired, so somehow the trigger is fired even when the browser is not scrolled to the element.

**Comment by Shrooma111** [comment]
Found it, personal bug..

**Comment by OvermindDL1** [comment]
What was the bug you had if you do not mind my asking?  It is good to document such fixes even in internal code for others to follow up.  :-)

**Comment by Shrooma111** [comment]
Actually, i thought this issue was related to the location of the intercooler js file in the html (in header or footer). However, i have this issue again without changing source. As such, it may be caused by a caching issue, I'll do some more research and get back to this issue.

**Comment by OvermindDL1** [comment]
If in Chrome then Chrome has an excellent developer setup, profiler, debugger, etc...  If you can test it then that should help, or if you can give us a URL to a page with the issue then we could look too.  :-)

**Comment by Shrooma111** [comment]
Can't really put a finger on it, you may check it out:

[](https://rijkstest.azurewebsites.net/polls/)

**Comment by OvermindDL1** [comment]
So let's see, debugging in, it appears that `isScrolledIntoView` is returning true, so looking in it while I am currently scrolled near, but not at the top of the page, while the the bottom of the page continues to zoom away, reveals:
```
docViewTop -> 160
docViewBottom -> 2782
elemTop -> 1259
elemBottom -> 1279
```
Which is all reasonable I guess, the docViewTop is the top of the visible area, the docViewBottom is the bottom of the *entire* page minus the docViewTop.  Then this return is executed:
```javascript
    return ((elemBottom >= docViewTop) && (elemTop <= docViewBottom)
    && (elemBottom <= docViewBottom) && (elemTop >= docViewTop));
```
Well, `elemBottom >= docViewTop` is true, and `elemTop <= docViewBottom` is true, and `elemBottom <= docViewBottom` is true, and `elemTop >= docViewTop` is true, thus everything is true and it returns true, so it will load more data.  And when the page size changes the scroll event is caused again, causing more to load, and more, and more, and more.

So, http://intercoolerjs.org/examples/infinitescroll.html does not act this way, let's check it.  Basically the same except docViewBottom-docViewTop is the size of my actual screen, so some-how your page is enlarging the visible default screen, interesting.

Indeed, watching `$(window).height()` shows it to be increasing significantly over even the first few seconds of your page while `$(window).scrollTop()` remains at 0.

Unsure of reason, looks like jQuery is broken as far as I can tell (and you are using a **VERY** old version of jQuery) because `window.innerHeight` returns the correct value.

If anything `$(window).height()` should be `window.innerHeight` (and its faster too) and `$(window).scrollTop()` should be `window.pageYOffset`, and could replace the offset things too really, too much jQuery use here seems to be breaking it, but at the very least `$(window).height()` should be `window.innerHeight` to fix it.

I do notice one oddity though, all of your head tags are parsed into the body of the DOM, and although your head tags are inconsistent it does not look like you should have that kind of problem with those, makes me wonder if some of your other javascript imports are causing an issue (this is why I like the module system in ES6, only use when you ask for).

**Comment by Shrooma111** [comment]
Thanks for your intensive research, much appreciated!

Turned out to be an issue with the html. The served html consists of a html 'master', coded in utf-8 without BOM, part of which is extended by a 'child' html template, which turned out to be coded in utf-8 with BOM. Apparently, chrome doesn't handle this right and the doctype disappeared on the page resulting in de oddity you describe, and the incorrect amount of pixels for window height).

I got this hint [here ](http://stackoverflow.com/questions/24874486/too-big-number-of-window-height-on-wordpress)on stackoverflow.

So Jquery version was not an issue thankfully. By the way, the very old version is shown on the download page of intercooler?

**Comment by OvermindDL1** [comment]
Ahh, fascinating!  I'd not have guessed that.

jQuery is 'mostly' forward compatible, and is for what Intercooler uses, I think it is just shown that to be the oldest version it works with, but it works fine with 3.x+ in my experience.
