### ISSUE TITLE
Add Global Headers in jQuery?

### ISSUE THREAD

**Issue by joexanderson** [LeadDyno/intercooler-js#125]
Hi,

I happened to stumble across Intercooler and I think I'll be glad I did. It looks awesome. But I'm having a problem using it with Laravel since it needs the CSRF token.

How can I set global headers in my jQuery? I understand that I can use defaults on a page, but I would rather have it set globally.

I'm currently just using .ajaxSetup but it appears I could use Intercooler's beforeSend function. I just don't see how to actually use it.

If you could help me, that would be greatly appreciated. Thanks!

**Comment by carsongross** [comment]
Hi Joseph,

Since intercooler uses jQuery under the covers, you can use the usual $.ajaxSetup() function to include additional metadata.

If you want to stay within intercooler, you can use an ic-global-include attribute on your page somewhere to include the token, using the JSON format or a hidden input referenced via CSS selector, according to tastes. :)

Cheers,
Carson

On September 28, 2016 at 4:10:36 PM, Joseph Anderson (notifications@github.com) wrote:

Hi,

I happened to stumble across Intercooler and I think I'll be glad I did. It looks awesome. But I'm having a problem using it with Laravel since it needs the CSRF token.

How can I set global headers in my jQuery? I understand that I can use defaults on a page, but I would rather have it set globally.

If you could help me, that would be greatly appreciated. Thanks!

**Comment by joexanderson** [comment]
@carsongross Awesome! Thanks so much, got it.
