### ISSUE TITLE
Website: legacy file examples.html in web root (not in tree) is broken, but indexed in Google

### ISSUE THREAD

**Issue by artjomsimon** [LeadDyno/intercooler-js#143]
I was googling for "intercooler input example", and Google listed http://intercoolerjs.org/examples.html as first result.

This file (which isn't even in the repo anymore) uses release 0.4.6. The examples don't work, the JS console log is full of errors.

This is not a bug per se, but for the sake of documentation consistency and to help new users find the examples in /examples/index.html, I propose the old file examples.html should be deleted from the web root (and the URL forwarded to /examples/index.html if you wish) so that google doesn't list it in the search results.

**Comment by carsongross** [comment]
Wow, that’s an old one!

I’ll fix that up, thanks for the tip!

Cheers,
Carson

On December 2, 2016 at 3:17:08 AM, Artjom Simon (notifications@github.com)
wrote:

I was googling for "intercooler input example", and Google listed
http://intercoolerjs.org/examples.html as first result.

This file uses release 0.4.6 which isn't even in the repo anymore. The
examples don't work, the JS console log is full of errors.

This is not a bug per se, but for the sake of documentation consistency and
to help new users find the examples in /examples/index.html, I propose the
old file examples.html should be deleted from the web root (and the URL
forwarded to /examples/index.html if you wish) so that google doesn't list
it in the search results.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/LeadDyno/intercooler-js/issues/143>, or mute the thread

**Comment by carsongross** [comment]
OK, I have a redirection page up there now.  Thank you for the tip!
