### ISSUE TITLE
Error when setting up CodePen demo with Intercooler.js

### ISSUE THREAD

**Issue by impressivewebs** [LeadDyno/intercooler-js#148]
Any idea why CodePen is throwing an error here?

http://codepen.io/SitePoint/pen/1be743a859e9e056facbbc61347a181c

CodePen allows Ajax, as long as the requested page is hosted on CodePen. You can see the `ic-post-to` attribute pointing to a CodePen .html page. So it should work. I've confirmed with Chris Coyier, one of the CodePen devs/creators, he says he can't figure out why it's not working. Oddly, the "Request Method" in the headers is listed as "OPTIONS", instead of "GET", which is strange. You can see this [in this screenshot](http://d.pr/i/VY26/iunGa5XQ) which compares a successful request using regular Ajax.

This could be a CodePen problem, but I just wanted to run it by you and see if maybe it was related to Intercooler.js itself. Thanks!

**Comment by carsongross** [comment]
It's a cross domain issue, which is why you are seeing the OPTIONS request.

I'm not an expert in this area, but someone nicely added some docs around
the issue:

http://intercoolerjs.org/docs.html#cross-domain

Cheers,
Carson


On December 15, 2016 at 4:07:07 PM, Louis Lazaris (notifications@github.com)
wrote:

Any idea why CodePen is throwing an error here?

http://codepen.io/SitePoint/pen/1be743a859e9e056facbbc61347a181c

CodePen allows Ajax, as long as the requested page is hosted on CodePen.
You can see the ic-post-to attribute pointing to a CodePen .html page. So
it should work. I've confirmed with Chris Coyier, one of the CodePen
devs/creators, he says he can't figure out why it's not working. Oddly, the
"Request Method" in the headers is listed as "OPTIONS", instead of "GET",
which is strange. You can see this in this screenshot
<http://d.pr/i/VY26/iunGa5XQ> which compares a successful request using
regular Ajax.

This could be a CodePen problem, but I just wanted to run it by you and see
if maybe it was related to Intercooler.js itself. Thanks!

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/LeadDyno/intercooler-js/issues/148>, or mute the thread

**Comment by impressivewebs** [comment]
That's strange because CodePen is set up to allow those requests as long as the requested data is on a CodePen hosted page. So that issue is already addressed. For example, you can see a basic jQuery-based Ajax request [on CodePen here](https://codepen.io/SitePoint/pen/38467ada2ca410b7e4d2d1cc70010499.html). That works fine, so the correct headers are in place. But why doesn't it work with Intercooler?

I tried the `withCredentials` part of that page you linked to, but that didn't work either, so I'm not sure what else to do. Like I said, it could be CodePen specific, but it's just strange that other Ajax requests work fine on CodePen, but not with Intercooler.
