### ISSUE TITLE
ic-include multilevel JSON

### ISSUE THREAD

**Issue by spajz** [LeadDyno/intercooler-js#155]
Hi,
excellent library.
Is it multilevel JSON supported like ic-include parameter?
For example:
```
ic-include='{"data":"action","param1":false,"obj":[{"name": "test1"}, {"name": "test2"}]}'
```
I get something like this in request:
```
ic-request=true&&ic-id=2&data=action&param1=false&obj=%5Bobject+Object%5D%2C%5Bobject+Object%5D&ic-current-url=%2Fadmin%2Fuser&_method=POST
```
Deeper levels as just an Object.
It is possible to use a multidimensional JSON in any way?

Thanks

**Comment by carsongross** [comment]
Hmmm.  We should probably serialize an object for inclusion, shouldn't we?

Cheers,
Carson

On January 7, 2017 at 6:01:57 AM, Djordje Dimitrijev (
notifications@github.com) wrote:

Hi,
excellent library.
Is it multilevel JSON supported like ic-include parameter?
For example:

ic-include='{"data":"action","param1":false,"obj":[{"name": "test1"},
{"name": "test2"}]}'

I get something like this in request:

ic-request=true&&ic-id=2&data=action&param1=false&obj=%5Bobject+Object%5D%2C%5Bobject+Object%5D&ic-current-url=%2Fadmin%2Fuser&_method=POST

Deeper levels as just an Object.
It is possible to use a multidimensional JSON in any way?

Thanks

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/LeadDyno/intercooler-js/issues/155>, or mute the thread
