### ISSUE TITLE
targeted ic-confirm on elements parent

### ISSUE THREAD

**Issue by ygwain** [LeadDyno/intercooler-js#161]
There is a list of items, every single item can be edited or removed. E.g.:
```html
<ul ic-confirm="Are you sure?">
    <li>
        Item 1
       <a ic-get-from="items/1/edit" ic-target="closest li">Edit</a>
       <a ic-delete-from="items/1/delete">Delete</a>
     </li>
    <li>...</li>
</ul>
```
Is there a way to trigger confirmation only for delete action?
Is there a way to integrate libs like bootboxjs in easy way?

Thanks in advance.

**Comment by carsongross** [comment]
You'll have to inline it on the delete links....


On January 29, 2017 at 8:03:28 AM, ygwain (notifications@github.com) wrote:

There is a list of items, every single item can be edited or removed. E.g.:

<ul ic-confirm="Are you sure?">
    <li>
        Item 1
       <a ic-get-from="items/1/edit" ic-target="closest li">Edit</a>
       <a ic-delete-from="items/1/delete">Delete</a>
     </li>
    <li>...</li>
</ul>

Is there a way to trigger confirmation only for delete action?
Is there a way to integrate libs like bootboxjs in easy way?

Thanks in advance.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/LeadDyno/intercooler-js/issues/161>, or mute the thread
