### ISSUE TITLE
ic-trigger-on="focusout submit" on a form element is working incorrectly?

### ISSUE THREAD

**Issue by ygwain** [LeadDyno/intercooler-js#162]
```html
<form ic-post-to="/edit" ic-target="closest span" ic-trigger-on="focusout submit">
    <input type="text" name="name" value="Item">
</form>
```
In case above only first event is working. If you swap it to "submit focusout", submit will work.

**Comment by carsongross** [comment]
We don't currently support multiple actions in ic-trigger-on.  We should,
but we don't yet.

On January 29, 2017 at 10:37:44 AM, ygwain (notifications@github.com) wrote:

<form ic-post-to="/edit" ic-target="closest span"
ic-trigger-on="focusout submit">
    <input type="text" name="name" value="Item">
</form>

In case above only first event is working. If you swap it to "submit
focusout", submit will work.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/LeadDyno/intercooler-js/issues/162>, or mute the thread

**Comment by Largo** [comment]
This doesn't seem to work yet for me. Would be very nice too have.
