### ISSUE TITLE
Replace only with partial HTML structure

### ISSUE THREAD

**Issue by brejoc** [LeadDyno/intercooler-js#169]
Would it be possible to use `ic-get-from` and `ic-post-to` to replace my elements content not with the full response, but Instead only a part of the HTML structure I get from the request?

The answer might e.g. look like this:
```HTML
<html>
  <head>…</head>
  <body>
    <div id="content">
      <p>Hello world!</p>
    </div>
  </body>
</html>
```

But only everything from (and perhaps including) '#content' should be used.

**Comment by carsongross** [comment]
Yep!

  http://intercoolerjs.org/attributes/ic-select-from-response.html

Now how much would you pay?  ;)

Cheers,
Carson

On February 22, 2017 at 3:12:46 AM, Jochen Breuer (notifications@github.com)
wrote:

Would it be possible to use ic-get-from and ic-post-to to replace my
elements content not with the full response, but Instead only a part of the
HTML structure I get from the request?

The answer might e.g. look like this:

<html>
  <head>…</head>
  <body>
    <div id="content">
      <p>Hello world!</p>
    </div>
  </body>
</html>

But only everything from (and perhaps including) '#content' should be used.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/LeadDyno/intercooler-js/issues/169>, or mute the thread

**Comment by brejoc** [comment]
This is awesome. I owe you a :beer: or two. Just looked into the guide, not into the reference. Sorry! :)
