### ISSUE TITLE
Replacing body TurboLinks style not working

### ISSUE THREAD

**Issue by brejoc** [LeadDyno/intercooler-js#175]
Seems like replacing the whole body TurboLinks style isn't working. The server gets the request and sends the correct response, but the page turns white. 

This is how the link looks like: `<a ic-get-from="/foo/" ic-target="body" ic-select-from-response="body">replace body</a>`

Wrapping the content of body in a `div` and replacing the `div` on the other hand works flawlessly:
`<a ic-get-from="/foo/" ic-target="#body-wrapper" ic-select-from-response="#body-wrapper">replace body-wrapper</a>`

It is also not possible to address the body in any other way, e.g. id-attribute.

A more complete example. I have this page:
```
<!DOCTYPE html>
<html>
  <head>
    <title>hello world</title>
    <script src="/static/adminlte-2.3.0/plugins/jQuery/jQuery-2.1.4.min.js"></script>
    <script src="/static/intercoolerjs/js/intercooler.min.js"></script>
  </head>
  <body>
    <p>hello world</p>
    <a ic-get-from="/foo/" ic-target="body" ic-select-from-response="body">replace body</a>
  </body>
</html>
```

Clicking the link should replace the body with the body contents from the response like this:

```
<!DOCTYPE html>
<html>
  <head>
    <title>hello world</title>
    <script src="/static/adminlte-2.3.0/plugins/jQuery/jQuery-2.1.4.min.js"></script>
    <script src="/static/intercoolerjs/js/intercooler.min.js"></script>
  </head>
  <body>
    <p>hello intercooler</p>
  </body>
</html>
```

Although the response is correctly coming in, the result looks like this:

```
<!DOCTYPE html>
<html>
  <head>
    <title>hello world</title>
    <script src="/static/adminlte-2.3.0/plugins/jQuery/jQuery-2.1.4.min.js"></script>
    <script src="/static/intercoolerjs/js/intercooler.min.js"></script>
  </head>
  <body>
  </body>
</html>
```

**Comment by carsongross** [comment]
Hmmm.  This is a hard one to test.

Is using an inner div as the target unacceptable in the short run?

Cheers,
Carson


On March 3, 2017 at 4:17:54 AM, Jochen Breuer (notifications@github.com)
wrote:

Seems like replacing the whole body TurboLinks style isn't working. The
server gets the request and sends the correct response, but the page turns
white.

This is how the link looks like: <a ic-get-from="/foo/" ic-target="body"
ic-select-from-response="body">replace body</a>

Wrapping the content of body in a div and replacing the div on the other
hand works flawlessly:
<a ic-get-from="/foo/" ic-target="#body-wrapper"
ic-select-from-response="#body-wrapper">replace body-wrapper</a>

It is also not possible to address the body in any other way, e.g.
id-attribute.

A more complete example. I have this page:

<!DOCTYPE html>
<html>
  <head>
    <title>hello world</title>
    <script src="/static/adminlte-2.3.0/plugins/jQuery/jQuery-2.1.4.min.js"></script>
    <script src="/static/intercoolerjs/js/intercooler.min.js"></script>
  </head>
  <body>
    <p>hello world</p>
    <a ic-get-from="/foo/" ic-target="body"
ic-select-from-response="body">replace body</a>
  </body>
</html>

Clicking the link should replace the body with the body contents from the
response like this:

<!DOCTYPE html>
<html>
  <head>
    <title>hello world</title>
    <script src="/static/adminlte-2.3.0/plugins/jQuery/jQuery-2.1.4.min.js"></script>
    <script src="/static/intercoolerjs/js/intercooler.min.js"></script>
  </head>
  <body>
    <p>hello intercooler</p>
  </body>
</html>

Although the response is correctly coming in, the result looks like this:

<!DOCTYPE html>
<html>
  <head>
    <title>hello world</title>
    <script src="/static/adminlte-2.3.0/plugins/jQuery/jQuery-2.1.4.min.js"></script>
    <script src="/static/intercoolerjs/js/intercooler.min.js"></script>
  </head>
  <body>
  </body>
</html>

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/LeadDyno/intercooler-js/issues/175>, or mute the thread

**Comment by brejoc** [comment]
That is exactly what we are doing as a workaround. Replacing the inner div works flawlessly.

**Comment by scottwoodall** [comment]
I researched this a bit and came across the following from the jQuery docs [1]:


> When passing in complex HTML, some browsers may not generate a DOM that exactly replicates the HTML source provided. As mentioned, jQuery uses the browser's .innerHTML property to parse the passed HTML and insert it into the current document. During this process, some browsers filter out certain elements such as <html>, <title>, or <head> elements. As a result, the elements inserted may not be representative of the original string passed.


I tracked this down to what I believe is the relevant Intercooler line:

```
 asQuery = $($.parseHTML(newContent, null, true));
```

`$.parseHTML()` isn't returning the `<body>` tag as mentioned in the jQuery docs.

[1] http://api.jquery.com/jquery/

**Comment by carsongross** [comment]
thanks scott for looking into this

if jquery doesn't support it, unfortunately I don't think intercooler should support it
