### ISSUE TITLE
Bug in click-to-edit example

### ISSUE THREAD

**Issue by ludaavics** [LeadDyno/intercooler-js#177]
In the [click to edit](http://intercoolerjs.org/examples/clicktoedit.html) example, amended inputs are saved even if user clicks on Cancel instead of Submit.

Could it be the Cancel button should be outside the form?

**Comment by carsongross** [comment]
That was a regression, I have released a new version that fixes the issue.
Thank you for finding it!


On March 4, 2017 at 8:04:24 AM, Ludovic Tiako (notifications@github.com)
wrote:

In the click to edit <http://intercoolerjs.org/examples/clicktoedit.html>
example, amended inputs are saved even if user clicks on Cancel instead of
Submit.

Could it be the Cancel button should be outside the form?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/LeadDyno/intercooler-js/issues/177>, or mute the thread
