### ISSUE TITLE
Publish v1.1.0 on npm?

### ISSUE THREAD

**Issue by artisin** [LeadDyno/intercooler-js#178]
I'm curious if there was a reason `1.1.0` was not published to npm.

**Comment by carsongross** [comment]
I just forgot to publish it, since I don't use NPM.  :)

Published now!

On March 5, 2017 at 7:08:16 PM, te (notifications@github.com) wrote:

I'm curious if there was a reason 1.1.0 was not published to npm.
Furthermore, 1.1.0 states "major implementation changes," and for the life
of me, I can't find the changelog. If there is a changelog can you please
point me in the right direction, and if not, are there breaking changes in
this release? Thanks!

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/LeadDyno/intercooler-js/issues/178>, or mute the thread
