### ISSUE TITLE
Can't find variable Zepto, when minifying

### ISSUE THREAD

**Issue by BrunoDeBarros** [LeadDyno/intercooler-js#180]
I'm using Intercooler in a project that uses Grunt to concat and minify all JS, and it seems to be transforming the line of code you added recently from something that doesn't throw any errors to something that does.

Your original code:

```
// work around zepto build issue TODO - fix me
  if((typeof Zepto) && ($ == null)) {
    $ = Zepto
  }
```

The minified code:

```
Zepto,null==$&&($=Zepto);
```

I think what's throwing it off is the fact that you're doing `(typeof Zepto)`, which is always true no matter what the type of the variable, because it's a non-empty string. I think you meant to do `(typeof Zepto === "undefined")`?

Alternatively, using `window["Zepto"]` also takes care of it.

**Comment by carsongross** [comment]
Sorry about that.  Mind putting a pull request against development together?

Cheers,
Carson

On March 9, 2017 at 7:28:37 AM, Bruno De Barros (notifications@github.com)
wrote:

I'm using Intercooler in a project that uses Grunt to concat and minify all
JS, and it seems to be transforming the line of code you added recently
from something that doesn't throw any errors to something that does.

Your original code:

// work around zepto build issue TODO - fix me
  if((typeof Zepto) && ($ == null)) {
    $ = Zepto
  }

The minified code:

Zepto,null==$&&($=Zepto);

I think what's throwing it off is the fact that you're doing (typeof Zepto),
which is always true no matter what the type of the variable, because it's
a non-empty string. I think you meant to do (typeof Zepto === "undefined")?

Alternatively, using window["Zepto"] also takes care of it.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/LeadDyno/intercooler-js/issues/180>, or mute the thread

**Comment by BrunoDeBarros** [comment]
Done! Thanks so much for all your hard work. As I've said before, Intercooler is fantastic. 😄
