### ISSUE TITLE
Zepto not defined in intercooler.min.js

### ISSUE THREAD

**Issue by DBPreston** [LeadDyno/intercooler-js#186]
Using Intercooler 1.1.1 minified version from cdnjs.cloudflare.com, I'm getting "Uncaught ReferenceError: Zepto is not defined" error in the console. This only happens with minified version, unminified is fine.

**Comment by carsongross** [comment]
Ugh, looks like I missed a deploy step.

I've updated the minified version and purged the CDN cache.  Can you try
again in an hour or so?

Sorry about that!


On March 20, 2017 at 5:48:45 AM, David Preston (notifications@github.com)
wrote:

Using Intercooler 1.1.1 minified version from cdnjs.cloudflare.com, I'm
getting "Uncaught ReferenceError: Zepto is not defined" error in the
console. This only happens with minified version, unminified is fine.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/LeadDyno/intercooler-js/issues/186>, or mute the thread

**Comment by DBPreston** [comment]
Hmmm, still getting the error. Could be cacheing at my end, but I tried adding a query string to force a reload but to no effect.

TBH it isn't a deal breaker for me as the unminified version works fine, but it could maybe trip up others.

**Comment by schpet** [comment]
i ran into this issue as well, with version 1.1.1 from npm. typical rails, asset pipeline, uglifier setup. 

it worked fine locally, but i got the zepto error in the minified production build. i'm using 'dist/intercooler' from the yarn/npm package.

**Comment by carsongross** [comment]
It seems like minification is breaking the zepto check.

Anyone have decent minificationfoo?

I'll release a fix as soon as I can.

Cheers,
Carson


On April 27, 2017 at 4:45:51 PM, Peter Schilling (notifications@github.com)
wrote:

i ran into this issue as well, with version 1.1.1 from npm. typical rails,
asset pipeline, uglifier setup.

it worked fine locally, but i got the zepto error in the minified
production build. i'm using 'dist/intercooler' from the yarn/npm package.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/LeadDyno/intercooler-js/issues/186#issuecomment-297869313>,
or mute the thread

**Comment by carsongross** [comment]
I've tried to merge the fix.

**Comment by schpet** [comment]
@carsongross cool! let me know if #196 needs any changes :v:

**Comment by A973C** [comment]
I'm still getting the error too by now. I had to use CDN link provided in homepage:
https://intercoolerreleases-leaddynocom.netdna-ssl.com/intercooler-1.1.1.min.js

**Comment by carsongross** [comment]
Ugh, looks like the docs and code got out of sync when I accepted a fix.

I will add a regression test and fix it in the next release.  Let me know
if you need a local fix before that.

Sorry for the regression!


On April 29, 2017 at 3:08:25 AM, Arnaud (notifications@github.com) wrote:

I'm still getting the error too by now. I had to use CDN link provided in
homepage:
https://intercoolerreleases-leaddynocom.netdna-ssl.com/intercooler-1.1.1.min.js

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/LeadDyno/intercooler-js/issues/186#issuecomment-298159834>,
or mute the thread
