### ISSUE TITLE
Using with Rails, how best to get form URL from FormBuilder to ic-get / ic-post / ic-put 

### ISSUE THREAD

**Issue by adambedford** [LeadDyno/intercooler-js#188]
Has anyone got an elegant solution for using Intercooler with Rails form builders to populate the `ic-post-to` / `ic-patch-to` etc attribute from the form's URL without hard coding it?

For example:

`simple_form_for [:account, @user] do |f|` results in a form with `action=account_users_path` and the `method` depends on whether the record is persisted. 

I could imagine setting these attributes on the client side for forms with `data-behavior="ic"` or something, but it'd be nice to find a better way.

**Comment by carsongross** [comment]
I created a helper in application_helper.rb that jams in the HTML
attributes:

  https://gist.github.com/carsongross/67490ce6c20398f1ecfb5331ec8dbabf

I've intended to put together a gem to help rails developers use
intercooler, but have never found the time.  If you re interested, let me
know.  :)

Cheers,
Carson

On March 22, 2017 at 12:42:39 PM, Adam Bedford (notifications@github.com)
wrote:

Has anyone got an elegant solution for using Intercooler with Rails form
builders to populate the ic-post-to / ic-patch-to etc attribute from the
form's URL without hard coding it?

For example:

simple_form_for [:account, @user] do |f| results in a form with
action=account_users_path and the method depends on whether the record is
persisted.

I could imagine setting these attributes on the client side for forms with
data-behavior="ic" or something, but it'd be nice to find a better way.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/LeadDyno/intercooler-js/issues/188>, or mute the thread
