### ISSUE TITLE
Default ic-indicator for all request

### ISSUE THREAD

**Issue by tiglui96** [LeadDyno/intercooler-js#203]
Hi!

It is possible to set a default Attribute for all intercooler calls?
I would like to avoid repeating the same code several times.

Thanks in advance and congratulations for this simple and excellent framework!

**Comment by carsongross** [comment]
Do you mean a parameter?  Would ic-global-include be what you want?

Otherwise, most intercooler attributes are inherited from their parents, so
you can place the attribute on a parent element for all sub-elements to get
all enclosed elements to behave the same way.

Glad you are finding intercooler useful.  Please tell all your friends and
followers.  :)

Cheers,
Carson

On May 24, 2017 at 7:31:02 AM, tiglui96 (notifications@github.com) wrote:

Hi!

It is possible to set a default Attribute for all intercooler calls?
I would like to avoid repeating the same code several times.

Thanks in advance and congratulations for this simple and excellent
framework!

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/LeadDyno/intercooler-js/issues/203>, or mute the thread

**Comment by tiglui96** [comment]
Thank you! The second answer was what I was looking for.
Placing ic-indicator  in a div which contains all the page, it is apply for all the intercooler calls.
