### ISSUE TITLE
Common ic-get-from for multiple inputs

### ISSUE THREAD

**Issue by Praucsc** [LeadDyno/intercooler-js#206]
Hi, 

If there are multiple input elements which use the same **ic-get-from** (or ic-post-to), how to avoid specifying the url name in each and every input ?

i.e. 
Is there a way I can write a common js to set the **ic-get-from** (by targeting jquery selector) value before send the ajax request. 
I saw http://intercoolerjs.org/examples/modifying_requests.html to add the request parameters,but can we change the url ?

Prabu

**Comment by carsongross** [comment]
Unfortunately no, this is one attribute that isn't inherited.  Sorry about
that!


On June 7, 2017 at 6:28:03 AM, Praucsc (notifications@github.com) wrote:

Hi,

If there are multiple input elements which use the same *ic-get-from* (or
ic-post-to), how to avoid specifying the url name in each and every input ?

i.e.
Is there a way I can write a common js to set the *ic-get-from* (by
targeting jquery selector) value before send the ajax request.
I saw http://intercoolerjs.org/examples/modifying_requests.html to add the
request parameters,but can we change the url ?

Prabu

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/LeadDyno/intercooler-js/issues/206>, or mute the thread
