### ISSUE TITLE
Item duplication in the Sortable List demo

### ISSUE THREAD

**Issue by idubrov** [LeadDyno/intercooler-js#210]
Items (color names) are duplicated if you reorder them fast enough in the [Sortable list demo](
http://intercoolerjs.org/examples/sortablelist.html).

See the attached image below:

![image](https://user-images.githubusercontent.com/434788/27373683-26640f0c-5661-11e7-90e6-d490680e5c9c.png)

**Comment by carsongross** [comment]
Looks like the DOM isn't guaranteed to be settled when the 'sort' event is fired.  I've switched it to the 'end' event instead.

**Comment by carsongross** [comment]
Yes, it is fixed in the dev branch.


On June 21, 2017 at 3:01:57 PM, Ivan Dubrov (notifications@github.com)
wrote:

Given that I can still reproduce the issue, I assume that page wasn't
updated yet.

—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub
<https://github.com/LeadDyno/intercooler-js/issues/210#issuecomment-310217839>,
or mute the thread
