### ISSUE TITLE
Pointer cursor on <a> tags

### ISSUE THREAD

**Issue by deepakmn** [LeadDyno/intercooler-js#212]
How do I get the pointer cursor to appear when hovered over <a> tags? Currently, it's displaying only the text cursor even with style applied.

**Comment by carsongross** [comment]
Adding an href="#" should do it, but so should a simple CSS rule.


On July 20, 2017 at 11:06:57 AM, deepakmn (notifications@github.com) wrote:

How do I get the pointer cursor to appear when hovered over tags?
Currently, it's displaying only the text cursor even with style applied.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/LeadDyno/intercooler-js/issues/212>, or mute the thread
