### ISSUE TITLE
jQuery attached to the partial after a ic-put-to doesn't work

### ISSUE THREAD

**Issue by newterminator** [LeadDyno/intercooler-js#214]
So I am able to successfully do the following on a post show page with many comments: 
```html
<a ic-get-from="<%= edit_comment_path @comment %>"
   ic-target="#comment-<%= @comment.id %>">Edit</a>
```
And then 
```html
<a ic-put-to="<%= comment_path @comment %>"
   ic-target="#comment-<%= @comment.id %>">Save</a>
```
So intercooler-js works flawlessly in showing the edit form for any given single comment, and then updating the comment in place. The issue is that once the comment is shown after an update, the jQuery which is attached to the comment partial view does not work. 

The specific piece of code from the partial, on which the jQuery gets called :
```html
<a class="toggle" href="#toggle-comment-share-div-<%= @comment.id %>">share</a>
<div id="toggle-comment-share-div-<%= @comment.id %>">
   <div class="share" data-url="<%= url %>" data-text="<%= @post.title %>"></div>
</div>
```
The jquery that gets called when the `share` link is clicked does not work, though the other comments on the page with the link work. I searched for in the issues if someone else faced the same problem, but I didnt see it, also I apologize if I missed it being addressed in the documentation.

**Comment by carsongross** [comment]
How do you have your event listener wired in?

You may want to use the Intercooler.ready function (in place of the normal
jQuery ready):

Intercooler.ready(function(addedContent){
  addedContent.find("someSelector").on(...)
});

Cheers,
Carson

On August 11, 2017 at 3:37:23 PM, newterminator (notifications@github.com)
wrote:

So I am able to successfully do the following:

<a ic-get-from="<%= edit_comment_path @comment %>"
   ic-target="#comment-<%= @comment.id %>">Edit</a>

And then

<a ic-put-to="<%= comment_path @comment %>"
   ic-target="#comment-<%= @comment.id %>">Save</a>

So intercooler-js works flawlessly in showing the edit form, and then
updating the comment in place. The issue is that once the comment is shown
after an update, the jQuery which is attached to the partial view does not
work.

What I mean in terms of code is:

<a class="toggle" href="#toggle-comment-share-div-<%= @comment.id %>">share</a>
<div id="toggle-comment-share-div-<%= @comment.id %>">
   <div class="share" data-url="<%= url %>" data-text="<%= @post.title
%>"></div>
</div>

The jquery that gets called when the share link is clicked does not work,
though the other comments on the page with the link work. I searched for in
the issues if someone else faced the same problem, but I didnt see it, also
I apologize if I missed it being addressed in the documentation.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/LeadDyno/intercooler-js/issues/214>, or mute the thread

**Comment by newterminator** [comment]
Thanks for the quick reply @carsongross . Intercooler.ready did the trick. I also want to take the opportunity to thank you for making those rails videos. They are super helpful, even today, 3 years after being made, at least the first one I saw to get started, helped flawlessly, which is kinda nice in the ever changing/deprecating/obsolete messages world. Cheers.
