### ISSUE TITLE
how to trigger bootstrap modal

### ISSUE THREAD

**Issue by cucy** [LeadDyno/intercooler-js#235]
how to trigger bootstrap modal?

**Comment by carsongross** [comment]
there isn't anything particularly special about intercooler for client side stuff like modals: you can use events of client side actions to trigger stuff but by and large you just write the javascript you want client side

Here is an example using a bootstrap modal dialog as a confirmation UI.  Note that it is all plain old javascript until the custom event is triggered, which triggers an intercooler request

http://intercoolerjs.org/examples/bootstrap_confirm.html

**Comment by BoPeng** [comment]
Thanks for the example. What I am trying to do is the use of `ic-get-from` to load a modal dynamically (which seems to work), then use `ic-on-success="$('#loaded-modal').show();"` to show the modal, what does not. Manually trigger the `ic-on-success` function will show the dialog but the backdrop etc are all wrong. 

Note that my old method have multiple bootstrap modals hidden on the page and toggled with `data-toggle` of various buttons. I am trying to load the modals on-demand, when the buttons are clicked. The example you referred to has the effect I want, but I want to use plain `html` from templates, not `JS`.

**Comment by DNWEIJ** [comment]
Hi,
Pretty late to the party :-)
 
W`hen you load a div from your backend, it is just html.  Boostrap doesn't know about it, since the 'registration cycle' of boostrap runs during load of the page. So you need to tell boostrap you got a new modal that you would like to be handled by bootstrap, instead of having just a snippet of html.

It is pretty easy to do so:
`$("#myModal").modal()`  registers the loaded div as being a modal for boostrap. since we doing ajax load, we need a delay else it will not work. The solution is then:

```
<a  ..... ic-on-success='doActivate()'>  

function doActivate() {   
    setTimeout(function() { $("#myModal").modal().show() }, 50);   
}
```

The same applies if you load intercooler html dynamically, you need to register the html at intercooler.
`Intercooler.processNodes($('yourDiv'))`
