### ISSUE TITLE
how to unregister all events

### ISSUE THREAD

**Issue by sathio** [LeadDyno/intercooler-js#238]
I couldn't find a way to unregister all intercooler events.
sometimes I need to 

    Intercooler.processNodes('#element'); 

after an ajax request, but doing so it appends several event instead of replacing, so for example a post action is sent twice, and then three times and so on..

**Comment by carsongross** [comment]
You could unregister the events manually if you wanted to, but to be honest this isn't really orthodox intercooler.  If you look at Intercooler.ready(function(elt)), for example, it passes in the new element that has been swapped in explicitly so you can avoid hooking up event handlers multiple times.

Why do you need to process nodes outside of the normal intercooler workflow?

**Comment by sathio** [comment]
because I add new via ajax and older nodes for some reason fire events twice, i could probably try to register only new elements one by one but i really wanted an easier method to disable all / process all

**Comment by carsongross** [comment]
Hi sathio,

Sorry for the delay on responses on this, I have been busy with other projects.

I would encourage you to use HTML replacement rather than DOM manipulation to achieve what you want.  That's the more 'intercooler way'.

If you needs are dynamic enough, you might want to look at a different library that you use in conjunction with intercooler to achieve your goals.  I'm willing to admin that intercooler isn't perfect for every app/feature.  :)
