### ISSUE TITLE
Delegated Intercooler trigger on dinamic created elemets (ajax return/createElement)

### ISSUE THREAD

**Issue by tonybolzan** [LeadDyno/intercooler-js#262]
Intercooler don't work with elements created after your initialization or I missing something ?

**Comment by baumann74** [comment]
It should work on all elements inside the server response. But intercooler will not work on elements that become visible because of a client side swap (out of band content swap). In that case you should use "Intercooler.processNodes(elt)".

**Comment by carsongross** [comment]
Yep, exactly.  If you are putting content into your page out of band, you need to call Intercooler.processNodes().

Cheers,
Carson

On October 26, 2018 at 6:38:16 AM, Anders Baumann (notifications@github.com) wrote:

It should work on all elements inside the server response. But intercooler will not work on elements that become visible because of a client side swap (out of band content swap). In that case you should use "Intercooler.processNodes(elt)".

**Comment by tonybolzan** [comment]
Great, this works
Thanks
> But you documentation don't tell this with clarity.

**Comment by carsongross** [comment]
Where in the docs do you think it makes sense to put this?

Happy to add it.

Cheers,
Carson


On October 29, 2018 at 4:18:03 AM, Tonin R. Bolzan (notifications@github.com) wrote:

Great, this works
Thanks

But you documentation don't tell this with clarity.

**Comment by tonybolzan** [comment]
Add a quote in the reference saying that intercoolerjs do not process nodes in externally made requests, like jQuery.ajax.

And in Javascript API Reference the text "out of band content swap" don't make much sense, because i'm a Brazilian and my english is not very good.
