### ISSUE TITLE
invalid certificate for CDN

### ISSUE THREAD

**Issue by rickdog** [LeadDyno/intercooler-js#55]
getting certificate error on library load

Refused to load the script 'https://cdn.intercoolerjs.org/intercooler-0.4.10.js' because it violates the following Content Security Policy directive: "script-src assets-cdn.github.com collector-cdn.github.com".

**Comment by carsongross** [comment]
Hi Rick,

For https, you'll need to use maxcdn’s URL instead:

  https://intercoolerreleases-leaddynocom.netdna-ssl.com/intercooler-0.4.10.min.js

Cheers,
Carson

On May 17, 2015 at 12:03:52 AM, rickdog (notifications@github.com) wrote:

getting certificate error on library load

Refused to load the script 'https://cdn.intercoolerjs.org/intercooler-0.4.10.js' because it violates the following Content Security Policy directive: "script-src assets-cdn.github.com collector-cdn.github.com".
