### ISSUE TITLE
ic-put-to on form element does not work

### ISSUE THREAD

**Issue by ziscloud** [LeadDyno/intercooler-js#62]
I am try to submit a html form via ic-put-to, but the form is still submitted via POST method, here is my code:
```html
<form class="form-inline" ic-put-to="/example" ic-target="#refresh_target">
input text etc.....
<button type="submit" class="btn btn-info">Submit</button>
</form>
```
Do I use it wrong?

**Comment by carsongross** [comment]
Hi Tony,

Intercooler will always use a POST when submitting the request, due to cross browser issues with AJAX requests for non-GET or POST requests.  

We include two pieces of information to indicate the actual HTTP method:

* The `_method` parameter, which is compatible with Rails)
* The `X-HTTP-Method-Override`, which is a google standard

Details can be found here:

http://intercoolerjs.org/docs.html#requests

**Comment by ziscloud** [comment]
Very clear explanation, thank you very much.
