### ISSUE TITLE
Expose processHeaders()

### ISSUE THREAD

**Issue by webholics** [LeadDyno/intercooler-js#63]
We currently have the case where we have another JS component on the page (a modal overlay) which integrates its own xhr logic for loading content.

We would like to process the xhr response with intercooler in order to have a common API (the intercooler response header) for the backend to talk with the frontend.

Therefore it would be helpful if the function processHeaders() could be included into the public Intercooler JS API. At the moment I don't see way get access to this functionality inside Intercooler.

**Comment by carsongross** [comment]
Hi Mario,

Sure, that’s a reasonable change.  Would you like to create a pull request?  :)

Cheers,
Carson

On October 16, 2015 at 1:31:21 AM, Mario Volke (notifications@github.com) wrote:

We currently have the case where we have another JS component on the page (a modal overlay) which integrates its own xhr logic for loading content.

We would like to process the xhr response with intercooler in order to have a common API (the intercooler response header) for the backend to talk with the frontend.

Therefore it would be helpful if the function processHeaders() could be included into the public Intercooler JS API. At the moment I don't see way get access to this functionality inside Intercooler.

**Comment by webholics** [comment]
Thanks I will. Just give me some days.
