### ISSUE TITLE
Docs for beforeTrigger shows docs for beforeSend

### ISSUE THREAD

**Issue by ninthspace** [LeadDyno/intercooler-js#69]
This page: http://intercoolerjs.org/attributes/ic-on-beforeTrigger.html shows the documentation for ic-on-beforeSend.

Looking at the code indicates that the available symbols should be event and element, rather than data, settings, xhr.

**Comment by carsongross** [comment]
Thanks for pointing that out, I will get it cleaned up.

Cheers,
Carson

On December 22, 2015 at 7:13:53 AM, Chris Aves (notifications@github.com) wrote:

This page: http://intercoolerjsorg/attributes/ic-on-beforeTriggerhtml shows the documentation for ic-on-beforeSend

Looking at the code indicates that the available symbols should be event and element, rather than data, settings, xhr
