### ISSUE TITLE
Lazy Loading A Div documentation - something is off

### ISSUE THREAD

**Issue by dotnetchris** [LeadDyno/intercooler-js#76]
http://intercoolerjs.org/examples/lazyload.html

> A progress indicator is nested in the div with the ic-indicator class on it, 

But there's no usage of `ic-indicator` either in the Source Code button or actually viewing the source of the page.

**Comment by carsongross** [comment]
Ah, good point.  In this case I just let the normal font awesome spinner go, since I want the spinner to show immediately.  I’ll fix the docs.

Cheers,
Carson

On January 22, 2016 at 8:54:13 AM, Chris Marisic (notifications@github.com) wrote:

http://intercoolerjsorg/examples/lazyloadhtml

A progress indicator is nested in the div with the ic-indicator class on it,

But there's no usage of ic-indicator either in the Source Code button or actually viewing the source of the page
