### ISSUE TITLE
ic-push-url not working

### ISSUE THREAD

**Issue by vrtc** [LeadDyno/intercooler-js#77]
In this case, the ic-push-url not working
```html
 <input type="text" name="text" ic-push-url="true" ic-get-from="/get_url" ic-trigger-on="keyup changed"
                           ic-target=".wraper-list" ic-trigger-delay="500ms" placeholder="Enter Some Text"/>
```

How to make GET parameters passed in the address bar of the browser?

**Comment by carsongross** [comment]
In this case the best option would be to use the X-IC-PushURL response header in the response from the server to push only the parameters you want into the browser bar.  The problem is that intercooler sends up all sorts of parameters, so you need to specify which ones in particular should be part of the pushed URL.  

Make sense?
