### ISSUE TITLE
delay on ic-indicator

### ISSUE THREAD

**Issue by tahmasebi** [LeadDyno/intercooler-js#95]
Hi, 
1- How can I set custom delay to performing `ic-indicator`?
I want to display loading-spin, if loading a response take more than 500ms.

2- I want use both `ic-indicator` and css element transition together, so I want to
- fadeOut element
- display loading-spin
- fadeIn new data in element

are these possible?

Thank you for your amazing work.

**Comment by carsongross** [comment]
Hi There,

It is not currently documented, but if you include the 'ic-use-transition' class on your indicator, rather than hiding and showing the indicator it will remove the class while a request is in flight, and then readd it afterwards.  This, plus CSS transitions, should allow you to achieve what you want.  It would be a bit of work, but it could be done.  :)

I need to document that feature and also put together a nice image showing when we add and remove classes to make it easier to understand.

Thanks for the compliment, that's what keeps me going!

**Comment by carsongross** [comment]
I added a CSS example on the ic-indicator page:

http://intercoolerjs.org/attributes/ic-indicator.html

Hope that helps.

**Comment by tahmasebi** [comment]
Hi, Thank you,
I test this new css example, but it display indicator only once. because after receiving data, it adds `ic-use-transition` and `style="display:none;"` , you can see my tested code here:

```
      <div class="live-demo">
        <style>
          .css-demo.ic-use-transition {
            opacity: 0;
            font-size: 8px;
          }
          .css-demo {
            opacity: 1;
            font-size: 25px;
            transition: all 500ms;
          }
        </style>
        <button class="btn btn-lg btn-primary" ic-get-from="http://localhost/new/test.php" ic-push-url="true"; ic-indicator="#indicator-css">Click Me!</button>
        <div id="indicator-css" class="css-demo ic-use-transition">Loading</div>
      </div>
``` 

When I open html file directly, indicator works fine, but `test.php` response doesn't load to target element. but when I access from localhost, it loads `test.php` response and adds `style="display:none;"`  !!

**Comment by carsongross** [comment]
Are you replacing the HTML that the indicator is in?  That might be resetting the DOM.

Cheers,
Carson

On May 10, 2016 at 11:58:03 PM, Foad Tahmasebi (notifications@github.com) wrote:

Hi, Thank you,
I test this new css example, but it display indicator only once. because after receiving data, it adds ic-use-transition and style="display:none;" , you can see my tested code here:

      <div class="live-demo">
        <style>
          .css-demo.ic-use-transition {
            opacity: 0;
            font-size: 8px;
          }
          .css-demo {
            opacity: 1;
            font-size: 25px;
            transition: all 500ms;
          }
        </style>
        <button class="btn btn-lg btn-primary" ic-get-from="http://localhost/new/test.php" ic-push-url="true"; ic-indicator="#indicator-css">Click Me!</button>
        <div id="indicator-css" class="css-demo ic-use-transition">Loading</div>
      </div>

When I open html file directly, indicator works fine, but test.php response doesn't load to target element. but when I access from localhost, it loads test.php response and adds style="display:none;" !!

**Comment by tahmasebi** [comment]
I test it again and I found out the problem is `ic-push-url="true"`.

When I use `ic-push-url` intercooler-js hides indicator element by adding `style="display:none"` and don't show it again. so the indicator shown only once. 

this is second code I tested:

``` html
<html>
<head>
  <script src="http://code.jquery.com/jquery-1.10.2.min.js"></script>
  <script src="http://cdn.intercoolerjs.org/intercooler-0.9.6.min.js"></script>
<style>
.ic-use-transition{
	visibility:hidden;
}

</style>
</head>
<body>
	<a ic-get-from="http://localhost/test/ajax.php" ic-indicator="#indicator" ic-push-url="false" ic-target="#target">Click</a>
	<div id="indicator" class="ic-use-transition">loading...</div>
	
	<div id="target" ></div>
</body>
</html>
```

**Comment by tahmasebi** [comment]
@carsongross 
I think  the `ic-push-url` cause resetting the DOM.

When I use it, the color of `<body>` tag change in DevTools (blink)

**Comment by carsongross** [comment]
That should only happen when you press the back button.  Is that when you are seeing it?

Cheers,
Carson

On May 13, 2016 at 10:15:21 PM, Foad Tahmasebi (notifications@github.com) wrote:

@carsongross
I think the ic-push-url cause resetting the DOM.

When I use it, the color of <body> tag change in DevTools (blink)
