### ISSUE TITLE
Update documentation to reflect new AJAX verbs

### ISSUE THREAD

**Issue by jpincas** [LeadDyno/intercooler-js#99]
Unbelievably good piece of software - thank you so much for this!  Perhaps it would be a good idea to update the reference pages for the non 'GET' attributes likes 'ic-delete-from' and 'ic-put-to' to explain that they now don't actually use those verbs anymore and will default to POST in the AJAX request.  Would make things a lot easier for noobs like me!

**Comment by carsongross** [comment]
That’s a great idea, I will do so today.

If you wish to use the actual HTTP verbs (rather than a POST with the standard verb metadata) for them, you can use the following meta tag:

  <meta name="intercoolerjs:use-actual-http-method" content="true”/>

Just note that in some older browsers the requests may be issued as a GET without warning.

Thank you for the compliment!  

Cheers,
Carson

On May 26, 2016 at 12:11:33 AM, jpincas (notifications@github.com) wrote:

Unbelievably good piece of software - thank you so much for this! Perhaps it would be a good idea to update the reference pages for the non 'GET' attributes likes 'ic-delete-from' and 'ic-put-to' to explain that they now don't actually use those verbs anymore and will default to POST in the AJAX request. Would make things a lot easier for noobs like me!

**Comment by carsongross** [comment]
(cc’ing the mailing list)

Alright, I’ve updated all the HTTP action pages to include some information on the HTTP verbs:

  http://intercoolerjs.org/attributes/ic-put-to.html

Including a mention of the 

  <meta name="intercoolerjs:use-actual-http-method" content="true"/>

directive.

Also, Jiri pointed out that I could simplify my stock ticker example down to 8 attributes, from 10:

  http://intercoolerjs.org/2016/05/25/twelve-html-attributes-explained.html

A 33% savings over the original 12 attributes.  :)  Goes to show, even the guy who wrote most of intercooler sometimes forgets how simple it can make things...

Cheers,
Carson

On May 26, 2016 at 12:11:33 AM, jpincas (notifications@github.com) wrote:

Unbelievably good piece of software - thank you so much for this! Perhaps it would be a good idea to update the reference pages for the non 'GET' attributes likes 'ic-delete-from' and 'ic-put-to' to explain that they now don't actually use those verbs anymore and will default to POST in the AJAX request. Would make things a lot easier for noobs like me!

**Comment by carsongross** [comment]
Thanks Carson.

In the end I decided to go the way of using the actual HTTP verb with the 
meta tag in order to try to keep the back end development as clean as 
possible.  Trying to depend on request headers to route to the correct 
handlers would have been a nightmare.

Do we know how bad support for non GET/POST is and what browsers are 
affected? I've done some research but haven't found much information.

Again, thanks for the software, I've spent two full days with it now so am 
getting used to this quite unique way of building websites (e-commerce in 
my case) and am accumulating a list of questions/suggestions/enhancements - 
hopefully I'll be able to contribute to the project.  Here's a few points 
that I've encountered so far:

1.  Indicator specificity: perhaps I'm doing something wrong but yesterday 
I really struggled to get progress indicators where I needed them (think of 
a cart with various items).  I was either getting indicators on all the 
elements, or only the first one.  I tried using both the class technique 
and the attribute technique, but it seems support for progress indicator 
selection on parent elements could be enhanced.  I'll elaborate one I have 
full details.

2.  DOM-diffing (or something like that):  I know the intercooler 
philosophy is to keep it simply, which I fully support, so this might be 
overkill.  Basic idea would be to make content swaps a little more 
sophisticated by only rendering changed content using the type of 
techniques used by client side view frameworks like React, View.js or 
Riot.js.

3.  Variables in URLs: this is what I'm about to tackle today, so it could 
be a non-issue.  I need to find an elegant way of getting a value from 
browser's local storage into Intercooler request URLs.  I'll see how it 
goes and report back.

**Comment by carsongross** [comment]
I’d be happy to look at your code and figure out what’s going on with the indicators.

DOM-diffing is definitely in the future for intercooler.  I just need to find some time to think through the various alternatives and figure out if we can keep it simple.  Riot.js looks promising at only a few thousand lines of code, I’ll take a look at what they have going on.

On variables you have in local storage, two initial thoughts: depending on how you are doing things, there is a ic-global-include attribute: http://intercoolerjs.org/attributes/ic-global-include.html which can be used to encode global state in the DOM.  I often use it to capture some UI state for better transitions.  If that doesn’t work for you, you should be able to mutate the parameters of the ajax request by listening for the beforeSend.ic and beforeAjaxSend.ic events and mutating the parameters there.

Happy to help if you need to jump on a video chat.

Cheers,
Carson
—
LeadDyno • Co-Founder
@carson_gross

On May 27, 2016 at 12:50:19 AM, 'Jonathan Pincas' via intercooler-js (intercooler-js@googlegroups.com) wrote:

Thanks Carson.

In the end I decided to go the way of using the actual HTTP verb with the meta tag in order to try to keep the back end development as clean as possible.  Trying to depend on request headers to route to the correct handlers would have been a nightmare.

Do we know how bad support for non GET/POST is and what browsers are affected? I've done some research but haven't found much information.

Again, thanks for the software, I've spent two full days with it now so am getting used to this quite unique way of building websites (e-commerce in my case) and am accumulating a list of questions/suggestions/enhancements - hopefully I'll be able to contribute to the project.  Here's a few points that I've encountered so far:

1.  Indicator specificity: perhaps I'm doing something wrong but yesterday I really struggled to get progress indicators where I needed them (think of a cart with various items).  I was either getting indicators on all the elements, or only the first one.  I tried using both the class technique and the attribute technique, but it seems support for progress indicator selection on parent elements could be enhanced.  I'll elaborate one I have full details.

2.  DOM-diffing (or something like that):  I know the intercooler philosophy is to keep it simply, which I fully support, so this might be overkill.  Basic idea would be to make content swaps a little more sophisticated by only rendering changed content using the type of techniques used by client side view frameworks like React, View.js or Riot.js.

3.  Variables in URLs: this is what I'm about to tackle today, so it could be a non-issue.  I need to find an elegant way of getting a value from browser's local storage into Intercooler request URLs.  I'll see how it goes and report back.

On Thursday, 26 May 2016 17:08:52 UTC+2, Carson Gross wrote:
(cc’ing the mailing list)

Alright, I’ve updated all the HTTP action pages to include some information on the HTTP verbs:

  http://intercoolerjs.org/attributes/ic-put-to.html

Including a mention of the 

  <meta name="intercoolerjs:use-actual-http-method" content="true"/>

directive.

Also, Jiri pointed out that I could simplify my stock ticker example down to 8 attributes, from 10:

  http://intercoolerjs.org/2016/05/25/twelve-html-attributes-explained.html

A 33% savings over the original 12 attributes.  :)  Goes to show, even the guy who wrote most of intercooler sometimes forgets how simple it can make things...

Cheers,
Carson

On May 26, 2016 at 12:11:33 AM, jpincas (notifi...@github.com) wrote:

Unbelievably good piece of software - thank you so much for this! Perhaps it would be a good idea to update the reference pages for the non 'GET' attributes likes 'ic-delete-from' and 'ic-put-to' to explain that they now don't actually use those verbs anymore and will default to POST in the AJAX request. Would make things a lot easier for noobs like me!

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub

--
You received this message because you are subscribed to the Google Groups "intercooler-js" group.
To unsubscribe from this group and stop receiving emails from it, send an email to intercooler-js+unsubscribe@googlegroups.com.
For more options, visit https://groups.google.com/d/optout.
